language: objective-c
osx_image: xcode9.4
xcode_project: BreakPoint.xcodeproj
xcode_scheme: BreakPointTests

script:
    - pod repo update && pod install
    - xcodebuild -quiet clean build -sdk iphonesimulator -workspace BreakPoint.xcworkspace -scheme BreakPoint CODE_SIGNING_REQUIRED=NO
podfile: '/Podfile'